version: '3.8'

services:
  backend:
    build: ./backend
    container_name: cat-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: cat-frontend
    ports:
      - "3000:3000"
  
  ollama:
    build: ./ollama
    container_name: cat-ollama
    ports:
      - "11434:11434"